
---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Generated Template for a VPC"
Parameters:
  cidrBlockVpc:
    Default: "10.0.0.0/20"
    Type: String
    Description: "Enter a valid /20 cidr block."
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/20'
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref cidrBlockVpc
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}"
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: InternetGateway
      VpcId:
        Ref: VPC
  DmzRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-DmzRouteTable"
  DmzRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
      RouteTableId:
        Ref: DmzRouteTable
  NoInternetRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-NoInternetRouteTable"
  DmzSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref "VPC"
      AvailabilityZone: !Join ["", [!Ref "AWS::Region", "a"]]
      CidrBlock:
        !Select
        - 0
        - 'Fn::Cidr':
            - !Select
              - 0
              - 'Fn::Cidr':
                  - !Ref "cidrBlockVpc"
                  - 4
                  - 10
            - 8
            - 7
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-DmzSubnetA"
        - Key: "Layer"
          Value: "dmz"
        - Key: "LayerCidr"
          Value:
            !Select
            - 0
            - 'Fn::Cidr':
                - !Ref "cidrBlockVpc"
                - 4
                - 10
  DmzRouteTableAAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: DmzSubnetA
      RouteTableId:
        Ref: DmzRouteTable
  NATA:
    DependsOn: GatewayAttachment
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !Sub "${EIPA.AllocationId}"
      SubnetId:
        Ref: DmzSubnetA
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-NATA"
  EIPA:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  DmzSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref "VPC"
      AvailabilityZone: !Join ["", [!Ref "AWS::Region", "b"]]
      CidrBlock:
        !Select
        - 1
        - 'Fn::Cidr':
            - !Select
              - 0
              - 'Fn::Cidr':
                  - !Ref "cidrBlockVpc"
                  - 4
                  - 10
            - 8
            - 7
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-DmzSubnetB"
        - Key: "Layer"
          Value: "dmz"
        - Key: "LayerCidr"
          Value:
            !Select
            - 0
            - 'Fn::Cidr':
                - !Ref "cidrBlockVpc"
                - 4
                - 10
  DmzRouteTableBAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: DmzSubnetB
      RouteTableId:
        Ref: DmzRouteTable
  NATB:
    DependsOn: GatewayAttachment
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !Sub "${EIPB.AllocationId}"
      SubnetId:
        Ref: DmzSubnetB
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-NATB"
  EIPB:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  DmzSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref "VPC"
      AvailabilityZone: !Join ["", [!Ref "AWS::Region", "c"]]
      CidrBlock:
        !Select
        - 2
        - 'Fn::Cidr':
            - !Select
              - 0
              - 'Fn::Cidr':
                  - !Ref "cidrBlockVpc"
                  - 4
                  - 10
            - 8
            - 7
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-DmzSubnetC"
        - Key: "Layer"
          Value: "dmz"
        - Key: "LayerCidr"
          Value:
            !Select
            - 0
            - 'Fn::Cidr':
                - !Ref "cidrBlockVpc"
                - 4
                - 10
  DmzRouteTableCAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: DmzSubnetC
      RouteTableId:
        Ref: DmzRouteTable
  NATC:
    DependsOn: GatewayAttachment
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !Sub "${EIPC.AllocationId}"
      SubnetId:
        Ref: DmzSubnetC
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-NATC"
  EIPC:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  AppSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref "VPC"
      AvailabilityZone: !Join ["", [!Ref "AWS::Region", "a"]]
      CidrBlock:
        !Select
        - 0
        - 'Fn::Cidr':
            - !Select
              - 1
              - 'Fn::Cidr':
                  - !Ref "cidrBlockVpc"
                  - 4
                  - 10
            - 8
            - 7
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-AppSubnetA"
        - Key: "Layer"
          Value: "app"
        - Key: "LayerCidr"
          Value:
            !Select
            - 1
            - 'Fn::Cidr':
                - !Ref "cidrBlockVpc"
                - 4
                - 10
  AppRouteTableAAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: AppSubnetA
      RouteTableId:
        Ref: AppRouteTableA
  AppRouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-AppRouteTableA"
        - Key: "Layer"
          Value: "app"
  AppNATARoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: AppRouteTableA
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: NATA
  AppSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref "VPC"
      AvailabilityZone: !Join ["", [!Ref "AWS::Region", "b"]]
      CidrBlock:
        !Select
        - 1
        - 'Fn::Cidr':
            - !Select
              - 1
              - 'Fn::Cidr':
                  - !Ref "cidrBlockVpc"
                  - 4
                  - 10
            - 8
            - 7
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-AppSubnetB"
        - Key: "Layer"
          Value: "app"
        - Key: "LayerCidr"
          Value:
            !Select
            - 1
            - 'Fn::Cidr':
                - !Ref "cidrBlockVpc"
                - 4
                - 10
  AppRouteTableBAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: AppSubnetB
      RouteTableId:
        Ref: AppRouteTableB
  AppRouteTableB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-AppRouteTableB"
        - Key: "Layer"
          Value: "app"
  AppNATBRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: AppRouteTableB
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: NATB
  AppSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref "VPC"
      AvailabilityZone: !Join ["", [!Ref "AWS::Region", "c"]]
      CidrBlock:
        !Select
        - 2
        - 'Fn::Cidr':
            - !Select
              - 1
              - 'Fn::Cidr':
                  - !Ref "cidrBlockVpc"
                  - 4
                  - 10
            - 8
            - 7
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-AppSubnetC"
        - Key: "Layer"
          Value: "app"
        - Key: "LayerCidr"
          Value:
            !Select
            - 1
            - 'Fn::Cidr':
                - !Ref "cidrBlockVpc"
                - 4
                - 10
  AppRouteTableCAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: AppSubnetC
      RouteTableId:
        Ref: AppRouteTableC
  AppRouteTableC:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-AppRouteTableC"
        - Key: "Layer"
          Value: "app"
  AppNATCRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: AppRouteTableC
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: NATC
Outputs:
  DmzSubnetIDs:
    Description: A list of dmzSubnetsIDs
    Value:
      !Join
      - ', '
      - - !Ref "DmzSubnetA"
        - !Ref "DmzSubnetB"
        - !Ref "DmzSubnetC"
    Export:
      Name: !Sub "${AWS::StackName}-dmzSubnetIDs"
  AppSubnetIDs:
    Description: A list of appSubnetsIDs
    Value:
      !Join
      - ', '
      - - !Ref "AppSubnetA"
        - !Ref "AppSubnetB"
        - !Ref "AppSubnetC"
    Export:
      Name: !Sub "${AWS::StackName}-appSubnetIDs"
